-- Ensure all required columns exist on tests table
ALTER TABLE tests ADD COLUMN IF NOT EXISTS duration_minutes INT;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS total_marks INT;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS format TEXT;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'upcoming';
ALTER TABLE tests ADD COLUMN IF NOT EXISTS schedule_time TEXT;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id);

-- Questions table
CREATE TABLE IF NOT EXISTS questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4()
);

ALTER TABLE questions ADD COLUMN IF NOT EXISTS test_id UUID REFERENCES tests(id) ON DELETE CASCADE;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS subject TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS section TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS question_text TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS question_img TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS options JSONB;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS option_imgs JSONB;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS correct_answer TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS marks INTEGER DEFAULT 4;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS neg_marks INTEGER DEFAULT 1;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS explanation TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS explanation_img TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS order_index INTEGER;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS difficulty TEXT;


-- Test-to-batch join table (many-to-many)
CREATE TABLE IF NOT EXISTS test_target_batches (
    test_id UUID NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    batch_id UUID NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    PRIMARY KEY (test_id, batch_id)
);
